### PR TITLE
Add possibility to change props per key using globs

### PR DESCRIPTION
**Pull request by alexandrusavin**
This will enable the customization of props for uploaded files.
Ex.:
```yaml
custom:
  s3Sync:
    - bucketName: my-bucket
      localDir: dist/
      params:
        - index.html:
            CacheControl: 'no-cache'
```

### CODE REVIEW

**Comment by k1LoW** [comment]
👀

**Comment by alexandrusavin** [comment]
@k1LoW Eny thoughts on this PR?

**Comment by k1LoW** [comment]
Sorry for the late reply 🙏 
LGTM !! I checked this PR !!

**Comment by k1LoW** [comment]
Released as v1.5.0.

**Pull request merged**
