### PR TITLE
fix s3 params

### PR DESCRIPTION
**Pull request by robjcaskey**
fix s3 parameters being set from config file - allows setting ContenType by file extension among other things.

### CODE REVIEW

**Comment by k1LoW** [comment]
@robjcaskey 

Thank you for your commit !!! ( and sorry late reply )

Coud you show me example `params` you want to set ?

**Comment by k1LoW** [comment]
Maybe your YAML is invalid ?

## valid

https://nodeca.github.io/js-yaml/#yaml=LS0tCnBhcmFtczoKICAtICJpbmRleC5odG1sIjoKICAgICAgQ29udGVudFR5cGU6ICd0ZXh0L2h0bWwnCiAgLSAiLm1qcyI6CiAgICAgIENvbnRlbnRUeXBlOiAndGV4dC9qYXZhc2NyaXB0JwogIC0gIi8qLm1qcyI6CiAgICAgIENvbnRlbnRUeXBlOiAndGV4dC9qYXZhc2NyaXB0Jwo=

https://jsfiddle.net/8v254hsx/

## invalid

https://nodeca.github.io/js-yaml/#yaml=LS0tCnBhcmFtczoKICAtICJpbmRleC5odG1sIjoKICAgIENvbnRlbnRUeXBlOiAndGV4dC9odG1sJwogIC0gIi5tanMiOgogICAgQ29udGVudFR5cGU6ICd0ZXh0L2phdmFzY3JpcHQnCiAgLSAiLyoubWpzIjoKICAgIENvbnRlbnRUeXBlOiAndGV4dC9qYXZhc2NyaXB0Jwo=

**Comment by k1LoW** [comment]
Could you fix your YAML following ?

```yaml
  params:
    - "*.js":
          ContentEncoding: "gzip" 👈more 2 space indent
    - "*.css":
          ContentEncoding: "gzip" 👈more 2 space indent
    - "*.svg":
          CacheControl: "max-age=604800, public" 👈more 2 space indent
          ContentEncoding: "gzip" 👈more 2 space indent
    - "*.png":
          CacheControl: "max-age=604800, public" 👈more 2 space indent
```

**Comment by konradkalemba** [comment]
You're right, everything works like a charm now. My bad I didn't look at links you sent. Thanks!

**Comment by k1LoW** [comment]
👍

**Pull request closed without merging**
