### PR TITLE
support bucketNameKey in syncMetadata

### PR DESCRIPTION
**Pull request by chichicuervo**
I get an error when deploying with the new bucketNameKey feature.  this fixes it.

### CODE REVIEW

**Comment by chichicuervo** [comment]
I still get errors in newest versions w/o this patch

**Comment by nibynool** [comment]
@chichicuervo perhaps you could do a code review on it and get it closer to being merged?

**Comment by k1LoW** [comment]
@chichicuervo Thank you !!!

**Comment by k1LoW** [comment]
Released as v1.10.6.

**Pull request merged**
